import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { CrestShell, PageIntro } from "@/components/crest-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";

type ContactSearch={product?:string;quantity?:number};
export const Route=createFileRoute("/contact")({validateSearch:(s:Record<string,unknown>):ContactSearch=>{const result:ContactSearch={};if(typeof s["product"]==="string")result.product=s["product"];if(typeof s["quantity"]==="number")result.quantity=s["quantity"];return result},head:()=>({meta:[{title:"Contact & Visit CREST | Hyderabad"},{name:"description",content:"Visit the CREST architectural surfaces showroom in Hyderabad or request a product quote."},{property:"og:title",content:"Visit CREST Hyderabad"},{property:"og:description",content:"See, feel and choose premium surfaces in person."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Contact});
function Contact(){const search=Route.useSearch();const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const {error}=await supabase.from("enquiries").insert({name:String(fd.get("name")),phone:String(fd.get("phone")),email:String(fd.get("email")||"")||null,company:String(fd.get("company")||"")||null,delivery_location:String(fd.get("location")||"")||null,message:String(fd.get("message")||"")||null,product_name:search.product||null,quantity:search.quantity||1});setBusy(false);if(!error)setSent(true)}return <CrestShell><PageIntro eyebrow="Contact" title="Let's find your surface." copy="Visit our Hyderabad showroom or tell us about your project. Our material team will help narrow the right finish, scale and specification."/><main className="mx-auto grid max-w-[1600px] gap-16 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-[10px] uppercase tracking-[.16em]">CREST · Hyderabad</p><h2 className="mt-5 text-5xl">See. Feel. Choose.</h2><div className="mt-12 space-y-5 border-y py-8 text-sm"><p>Hyderabad, Telangana · Serving Pan-India</p><a className="block underline underline-offset-4" href="https://wa.me/" target="_blank" rel="noreferrer">WhatsApp CREST</a><a className="block underline underline-offset-4" href="mailto:hello@crestsurfaces.in">hello@crestsurfaces.in</a></div><p className="mt-6 text-xs leading-6 text-muted-foreground">Showroom address and telephone details can be added in the management area.</p></div><div>{sent?<div className="border-y py-16"><p className="text-[10px] uppercase tracking-[.16em] text-accent">Enquiry received</p><h2 className="mt-5 text-5xl">Thank you.</h2><p className="mt-5 text-sm text-muted-foreground">The CREST team will contact you shortly.</p></div>:<form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field name="name" label="Name" required/><Field name="company" label="Company"/><Field name="phone" label="Phone" type="tel" required/><Field name="email" label="Email" type="email"/><Field name="location" label="Delivery location"/><Field name="product" label="Product" value={search.product} disabled/><label className="sm:col-span-2"><span className="mb-2 block text-[10px] uppercase tracking-[.12em]">Message</span><Textarea name="message" className="min-h-32 rounded-none" placeholder="Tell us about your project and timeline"/></label><Button disabled={busy} className="sm:col-span-2">{busy?"Sending…":"Request quote"}</Button></form>}</div></main></CrestShell>}
function Field({label,...props}:{label:string}&React.ComponentProps<typeof Input>){return <label><span className="mb-2 block text-[10px] uppercase tracking-[.12em]">{label}</span><Input {...props} className="h-12 rounded-none"/></label>}